function [cameraParameters, estimationErrors, imagesUsedDetection, imagesUsedCalibration] = ...
    calculateCameraParametersImages(markerParameters, calibrationParameters, imagesPath)

[imagePoints, boardSize, imagesUsedDetection] = ...
    detectCheckerboardPoints(imagesPath);

if boardSize ~= markerParameters.boardSize
    warning('the board size detect is different than the one inputed in markerParameters.boardSize')
end

  [cameraParameters, estimationErrors, imagesUsedCalibration] = ...
      calculateCameraParametersPoints(...
      markerParameters,...
      calibrationParameters,...
      imagePoints);
