function cameraParams = createCameraParameter(markerParameters,calibrationParameters,cameraParams)
%Function that simply calls CameraParameter but uses different inputs
%   

 cameraParams = cameraParameters(...
    'WorldPoints', markerParameters.worldPoints, ...
    'IntrinsicMatrix', cameraParams.IntrinsicMatrix, ...
    'RotationVectors', cameraParams.RotationVectors, ...
    'TranslationVectors', cameraParams.TranslationVectors, ...
    'RadialDistortion', cameraParams.RadialDistortion, ...
    'TangentialDistortion', cameraParams.TangentialDistortion, ...
    'ImageSize', calibrationParameters.imageSize);

end

